/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package openbook.domain;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=openbook.domain.Book.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri May 14 16:05:41 EDT 2010")
public class Book_ {
    public static volatile SingularAttribute<Book,String> ISBN;
    public static volatile ListAttribute<Book,Author> authors;
    public static volatile SingularAttribute<Book,Inventory> inventory;
    public static volatile SingularAttribute<Book,Double> price;
    public static volatile SingularAttribute<Book,String> title;
    public static volatile SingularAttribute<Book,Integer> version;
}
