/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package openbook.domain;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=openbook.domain.Customer.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu May 13 20:18:23 CDT 2010")
public class Customer_ {
    public static volatile SingularAttribute<Customer,String> email;
    public static volatile SingularAttribute<Customer,Long> id;
    public static volatile SingularAttribute<Customer,String> name;
    public static volatile SingularAttribute<Customer,Integer> version;
}
