/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package openbook.domain;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=openbook.domain.Inventory.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu May 13 20:18:23 CDT 2010")
public class Inventory_ {
    public static volatile SingularAttribute<Inventory,Book> book;
    public static volatile SingularAttribute<Inventory,Integer> sold;
    public static volatile SingularAttribute<Inventory,Integer> supplied;
    public static volatile SingularAttribute<Inventory,Integer> version;
}
