/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package openbook.domain;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=openbook.domain.LineItem.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri May 14 16:05:41 EDT 2010")
public class LineItem_ {
    public static volatile SingularAttribute<LineItem,Book> book;
    public static volatile SingularAttribute<LineItem,Integer> index;
    public static volatile SingularAttribute<LineItem,PurchaseOrder> order;
    public static volatile SingularAttribute<LineItem,Integer> quantity;
}
