/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package openbook.domain;

import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import openbook.domain.PurchaseOrder.Status;

@javax.persistence.metamodel.StaticMetamodel
(value=openbook.domain.PurchaseOrder.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri May 14 16:05:41 EDT 2010")
public class PurchaseOrder_ {
    public static volatile SingularAttribute<PurchaseOrder,Customer> customer;
    public static volatile SingularAttribute<PurchaseOrder,Date> deliveredOn;
    public static volatile SingularAttribute<PurchaseOrder,Long> id;
    public static volatile ListAttribute<PurchaseOrder,LineItem> items;
    public static volatile SingularAttribute<PurchaseOrder,Date> placedOn;
    public static volatile SingularAttribute<PurchaseOrder,Status> status;
    public static volatile SingularAttribute<PurchaseOrder,Integer> total;
}
