/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Company2.class)
public class Company2_ {
    public static volatile SingularAttribute<Company2,Integer> id;
    public static volatile MapAttribute<Company2,Division,VicePresident> organization;
}
