/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Company1.class)
public class Company1_ {
    public static volatile SingularAttribute<Company1,Integer> id;
    public static volatile MapAttribute<Company1,Division,VicePresident> organization;
}
