/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Department2.class)
public class Department2_ {
    public static volatile SingularAttribute<Department2,Integer> deptId;
    public static volatile MapAttribute<Department2,EmployeePK2,Employee2> empMap;
}
