/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Department3.class)
public class Department3_ {
    public static volatile SingularAttribute<Department3,Integer> deptId;
    public static volatile MapAttribute<Department3,EmployeeName3,Employee3> emps;
}
