/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Department1.class)
public class Department1_ {
    public static volatile SingularAttribute<Department1,Integer> deptId;
    public static volatile MapAttribute<Department1,Integer,Employee1> empMap;
}
