/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Division.class)
public class Division_ {
    public static volatile SingularAttribute<Division,Integer> id;
    public static volatile SingularAttribute<Division,String> name;
}
