/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Embed_Embed.class)
public class Embed_Embed_ {
    public static volatile SingularAttribute<Embed_Embed,Embed> embed;
    public static volatile SingularAttribute<Embed_Embed,Integer> intVal1;
    public static volatile SingularAttribute<Embed_Embed,Integer> intVal2;
    public static volatile SingularAttribute<Embed_Embed,Integer> intVal3;
}
