/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Embed_Coll_Embed.class)
public class Embed_Coll_Embed_ {
    public static volatile ListAttribute<Embed_Coll_Embed,Embed> embeds;
    public static volatile SingularAttribute<Embed_Coll_Embed,Integer> intVal1;
    public static volatile SingularAttribute<Embed_Coll_Embed,Integer> intVal2;
    public static volatile SingularAttribute<Embed_Coll_Embed,Integer> intVal3;
}
