/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Embed_Embed_ToMany.class)
public class Embed_Embed_ToMany_ {
    public static volatile SingularAttribute<Embed_Embed_ToMany,Embed_ToMany> embed;
    public static volatile SingularAttribute<Embed_Embed_ToMany,Integer> intVal1;
    public static volatile SingularAttribute<Embed_Embed_ToMany,Integer> intVal2;
    public static volatile SingularAttribute<Embed_Embed_ToMany,Integer> intVal3;
}
