/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Embed_MappedToOne.class)
public class Embed_MappedToOne_ {
    public static volatile SingularAttribute<Embed_MappedToOne,EntityB1> bm;
    public static volatile SingularAttribute<Embed_MappedToOne,String> name1;
    public static volatile SingularAttribute<Embed_MappedToOne,String> name2;
    public static volatile SingularAttribute<Embed_MappedToOne,String> name3;
}
