/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Embed_ToOne.class)
public class Embed_ToOne_ {
    public static volatile SingularAttribute<Embed_ToOne,EntityB1> b;
    public static volatile SingularAttribute<Embed_ToOne,String> name1;
    public static volatile SingularAttribute<Embed_ToOne,String> name2;
    public static volatile SingularAttribute<Embed_ToOne,String> name3;
}
