/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Embed_Coll_Integer.class)
public class Embed_Coll_Integer_ {
    public static volatile SingularAttribute<Embed_Coll_Integer,Integer> intVal1;
    public static volatile SingularAttribute<Embed_Coll_Integer,Integer> intVal2;
    public static volatile SingularAttribute<Embed_Coll_Integer,Integer> intVal3;
    public static volatile SetAttribute<Embed_Coll_Integer,Integer> otherIntVals;
}
