/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Embed_ToMany.class)
public class Embed_ToMany_ {
    public static volatile ListAttribute<Embed_ToMany,EntityB1> bs;
    public static volatile SingularAttribute<Embed_ToMany,String> name1;
    public static volatile SingularAttribute<Embed_ToMany,String> name2;
    public static volatile SingularAttribute<Embed_ToMany,String> name3;
}
