/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Employee3.class)
public class Employee3_ {
    public static volatile SingularAttribute<Employee3,Department3> department;
    public static volatile SingularAttribute<Employee3,Integer> empId;
    public static volatile SingularAttribute<Employee3,EmployeeName3> name;
}
