/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Employee2.class)
public class Employee2_ {
    public static volatile SingularAttribute<Employee2,Department2> department;
    public static volatile SingularAttribute<Employee2,EmployeePK2> empPK;
}
