/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.EmployeeName3.class)
public class EmployeeName3_ {
    public static volatile SingularAttribute<EmployeeName3,String> fName;
    public static volatile SingularAttribute<EmployeeName3,String> lName;
}
