/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.EmployeePK2.class)
public class EmployeePK2_ {
    public static volatile SingularAttribute<EmployeePK2,Date> bDay;
    public static volatile SingularAttribute<EmployeePK2,String> name;
}
