/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Employee1.class)
public class Employee1_ {
    public static volatile SingularAttribute<Employee1,Department1> department;
    public static volatile SingularAttribute<Employee1,Integer> empId;
}
