/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.EntityA_Coll_String.class)
public class EntityA_Coll_String_ {
    public static volatile SingularAttribute<EntityA_Coll_String,Integer> age;
    public static volatile SingularAttribute<EntityA_Coll_String,Integer> id;
    public static volatile SingularAttribute<EntityA_Coll_String,String> name;
    public static volatile SetAttribute<EntityA_Coll_String,String> nickNames;
}
