/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.EntityB1.class)
public class EntityB1_ {
    public static volatile SingularAttribute<EntityB1,EntityA_Embed_MappedToOne> entityA;
    public static volatile SingularAttribute<EntityB1,Integer> id;
    public static volatile SingularAttribute<EntityB1,String> name;
}
