/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.EntityA_Embed_Coll_Embed.class)
public class EntityA_Embed_Coll_Embed_ {
    public static volatile SingularAttribute<EntityA_Embed_Coll_Embed,Integer> age;
    public static volatile SingularAttribute<EntityA_Embed_Coll_Embed,Embed_Coll_Embed> embed;
    public static volatile SingularAttribute<EntityA_Embed_Coll_Embed,Integer> id;
    public static volatile SingularAttribute<EntityA_Embed_Coll_Embed,String> name;
}
