/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.EntityA_Embed_MappedToOne.class)
public class EntityA_Embed_MappedToOne_ {
    public static volatile SingularAttribute<EntityA_Embed_MappedToOne,Integer> age;
    public static volatile SingularAttribute<EntityA_Embed_MappedToOne,Embed_MappedToOne> embed;
    public static volatile SingularAttribute<EntityA_Embed_MappedToOne,Integer> id;
    public static volatile SingularAttribute<EntityA_Embed_MappedToOne,String> name;
}
