/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.EntityA_Embed_Embed_ToMany.class)
public class EntityA_Embed_Embed_ToMany_ {
    public static volatile SingularAttribute<EntityA_Embed_Embed_ToMany,Integer> age;
    public static volatile SingularAttribute<EntityA_Embed_Embed_ToMany,Embed_Embed_ToMany> embed;
    public static volatile SingularAttribute<EntityA_Embed_Embed_ToMany,Integer> id;
    public static volatile SingularAttribute<EntityA_Embed_Embed_ToMany,String> name;
}
