/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.EntityA_Embed_Coll_Integer.class)
public class EntityA_Embed_Coll_Integer_ {
    public static volatile SingularAttribute<EntityA_Embed_Coll_Integer,Integer> age;
    public static volatile SingularAttribute<EntityA_Embed_Coll_Integer,Embed_Coll_Integer> embed;
    public static volatile SingularAttribute<EntityA_Embed_Coll_Integer,Integer> id;
    public static volatile SingularAttribute<EntityA_Embed_Coll_Integer,String> name;
}
