/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.EntityA_Coll_Embed_Embed.class)
public class EntityA_Coll_Embed_Embed_ {
    public static volatile SingularAttribute<EntityA_Coll_Embed_Embed,Integer> age;
    public static volatile ListAttribute<EntityA_Coll_Embed_Embed,Embed_Embed> embeds;
    public static volatile SingularAttribute<EntityA_Coll_Embed_Embed,Integer> id;
    public static volatile SingularAttribute<EntityA_Coll_Embed_Embed,String> name;
}
