/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.EntityA_Coll_Embed_ToOne.class)
public class EntityA_Coll_Embed_ToOne_ {
    public static volatile SingularAttribute<EntityA_Coll_Embed_ToOne,Integer> age;
    public static volatile SetAttribute<EntityA_Coll_Embed_ToOne,Embed_ToOne> embed1s;
    public static volatile SingularAttribute<EntityA_Coll_Embed_ToOne,Integer> id;
    public static volatile SingularAttribute<EntityA_Coll_Embed_ToOne,String> name;
}
