/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Item3.class)
public class Item3_ {
    public static volatile SingularAttribute<Item3,Integer> id;
    public static volatile MapAttribute<Item3,String,String> images;
}
