/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Item2.class)
public class Item2_ {
    public static volatile SingularAttribute<Item2,Integer> id;
    public static volatile MapAttribute<Item2,String,String> images;
}
