/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.Item1.class)
public class Item1_ {
    public static volatile SingularAttribute<Item1,Integer> id;
    public static volatile MapAttribute<Item1,String,String> images;
}
