/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.embed;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.embed.VicePresident.class)
public class VicePresident_ {
    public static volatile SingularAttribute<VicePresident,Company1> co;
    public static volatile SingularAttribute<VicePresident,Integer> id;
    public static volatile SingularAttribute<VicePresident,String> name;
}
