/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.meta;

import javax.persistence.metamodel.ListAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.meta.ArrayMember.class)
public class ArrayMember_ {
    public static volatile ListAttribute<ArrayMember,Byte> Array;
    public static volatile ListAttribute<ArrayMember,Byte> array;
}
