/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.meta;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.meta.Embed0.class)
public class Embed0_ {
    public static volatile SingularAttribute<Embed0,ImplicitFieldAccessSubclass> entity1;
    public static volatile SingularAttribute<Embed0,Long> f1;
}
