/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.meta;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.meta.ExplicitFieldAccessMixed.class)
public class ExplicitFieldAccessMixed_ {
    public static volatile SingularAttribute<ExplicitFieldAccessMixed,Long> f1;
    public static volatile SingularAttribute<ExplicitFieldAccessMixed,Integer> f2;
    public static volatile SingularAttribute<ExplicitFieldAccessMixed,ImplicitFieldAccessBase> f4;
    public static volatile SingularAttribute<ExplicitFieldAccessMixed,ImplicitFieldAccessBase> f5;
}
