/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.meta;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.meta.ExplicitPropertyAccess.class)
public class ExplicitPropertyAccess_ {
    public static volatile SingularAttribute<ExplicitPropertyAccess,String> f1;
    public static volatile SingularAttribute<ExplicitPropertyAccess,String> f3;
    public static volatile SingularAttribute<ExplicitPropertyAccess,String> f4;
    public static volatile SingularAttribute<ExplicitPropertyAccess,ImplicitFieldAccessBase> f5;
    public static volatile SingularAttribute<ExplicitPropertyAccess,ImplicitFieldAccessBase> f6;
}
