/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.meta;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.meta.ExplicitFieldAccess.class)
public class ExplicitFieldAccess_ {
    public static volatile SingularAttribute<ExplicitFieldAccess,Long> f1;
    public static volatile SingularAttribute<ExplicitFieldAccess,Integer> f2;
    public static volatile SingularAttribute<ExplicitFieldAccess,ImplicitFieldAccessBase> f4;
    public static volatile SingularAttribute<ExplicitFieldAccess,ImplicitFieldAccessBase> f5;
}
