/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.meta;

import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel(
    value=org.apache.openjpa.persistence.meta.ExplicitPropertyAccessMixed.class)
public class ExplicitPropertyAccessMixed_ {
    public static volatile Attribute<ExplicitPropertyAccessMixed,String> f1;
    public static volatile Attribute<ExplicitPropertyAccessMixed,
        ImplicitFieldAccessBase> f3;
    public static volatile Attribute<ExplicitPropertyAccessMixed,Integer> f4;
    public static volatile Attribute<ExplicitPropertyAccessMixed,Short> f5;
    public static volatile Attribute<ExplicitPropertyAccessMixed,
        ImplicitFieldAccessBase> f6;
}
