/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.meta;

import java.util.Date;
import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel(
    value=org.apache.openjpa.persistence.meta.
        ImplicitFieldAccessMappedSuperclass.class)
public class ImplicitFieldAccessMappedSuperclass_ {
    public static volatile Attribute<ImplicitFieldAccessMappedSuperclass,Date> 
        createTime;
    public static volatile Attribute<ImplicitFieldAccessMappedSuperclass,Long>
        id;
}
