/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.meta;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.meta.ImplicitFieldAccessMappedSuperclass.class)
public class ImplicitFieldAccessMappedSuperclass_ {
    public static volatile SingularAttribute<ImplicitFieldAccessMappedSuperclass,Date> createTime;
    public static volatile SingularAttribute<ImplicitFieldAccessMappedSuperclass,Long> id;
    public static volatile SingularAttribute<ImplicitFieldAccessMappedSuperclass,Integer> version;
}
