/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.meta;

import javax.persistence.metamodel.CollectionAttribute;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.meta.ImplicitFieldAccessBase.class)
public class ImplicitFieldAccessBase_ extends ImplicitFieldAccessMappedSuperclass_  {
    public static volatile SingularAttribute<ImplicitFieldAccessBase,Integer> boxedInt;
    public static volatile CollectionAttribute<ImplicitFieldAccessBase,ExplicitFieldAccess> collectionRelation;
    public static volatile SingularAttribute<ImplicitFieldAccessBase,String> f0;
    public static volatile ListAttribute<ImplicitFieldAccessBase,ExplicitFieldAccess> listRelation;
    public static volatile MapAttribute<ImplicitFieldAccessBase,Integer,ExplicitFieldAccess> mapRelationKeyBasic;
    public static volatile MapAttribute<ImplicitFieldAccessBase,ExplicitPropertyAccess,ExplicitFieldAccess> mapRelationKeyPC;
    public static volatile SingularAttribute<ImplicitFieldAccessBase,ExplicitFieldAccess> one2oneRelation;
    public static volatile SingularAttribute<ImplicitFieldAccessBase,Integer> primitiveInt;
    public static volatile SetAttribute<ImplicitFieldAccessBase,ExplicitFieldAccess> setRelation;
}
