/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.meta;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.meta.ImplicitFieldAccessSubclass.class)
public class ImplicitFieldAccessSubclass_ extends ImplicitFieldAccessBase_  {
    public static volatile SingularAttribute<ImplicitFieldAccessSubclass,ImplicitFieldAccessBase> base;
    public static volatile MapAttribute<ImplicitFieldAccessSubclass,Embed0,ExplicitPropertyAccess> mapRelationKeyEmbedded;
}
