/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.A.class)
public class A_ {
    public static volatile SingularAttribute<A,B> b;
    public static volatile SingularAttribute<A,Long> id;
    public static volatile SingularAttribute<A,String> name;
}
