/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel
(value=org.apache.openjpa.persistence.criteria.A.class)
public class A_ {
    public static volatile Attribute<A,B> b;
    public static volatile Attribute<A,Long> id;
    public static volatile Attribute<A,String> name;
}
