/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Account.class)
public class Account_ {
    public static volatile SingularAttribute<Account,Integer> balance;
    public static volatile SingularAttribute<Account,Long> id;
    public static volatile SingularAttribute<Account,Integer> loan;
    public static volatile SingularAttribute<Account,String> name;
    public static volatile SingularAttribute<Account,Person> owner;
    public static volatile SingularAttribute<Account,Customer> customer;
    public static volatile SingularAttribute<Account,Product> product;
}
