/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel(
    value=org.apache.openjpa.persistence.criteria.Address.class)
public class Address_ {
    public static volatile Attribute<Address,String> city;
    public static volatile Attribute<Address,String> country;
    public static volatile Attribute<Address,String> county;
    public static volatile Attribute<Address,Long> id;
    public static volatile Attribute<Address,String> state;
    public static volatile Attribute<Address,String> street;
    public static volatile Attribute<Address,CompUser> user;
    public static volatile Attribute<Address,String> zipCode;
}
