/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Address.class)
public class Address_ {
    public static volatile SingularAttribute<Address,String> city;
    public static volatile SingularAttribute<Address,String> country;
    public static volatile SingularAttribute<Address,String> county;
    public static volatile SingularAttribute<Address,Long> id;
    public static volatile SingularAttribute<Address,String> state;
    public static volatile SingularAttribute<Address,String> street;
    public static volatile SingularAttribute<Address,CompUser> user;
    public static volatile SingularAttribute<Address,String> zipCode;
}
