/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel
(value=org.apache.openjpa.persistence.criteria.B.class)
public class B_ {
    public static volatile Attribute<B,Integer> age;
    public static volatile Attribute<B,Long> id;
}
