/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.B.class)
public class B_ {
    public static volatile SingularAttribute<B,Integer> age;
    public static volatile SingularAttribute<B,Long> id;
}
