/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.CollectionAttribute;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.C.class)
public class C_ {
    public static volatile CollectionAttribute<C,D> coll;
    public static volatile SingularAttribute<C,Long> id;
    public static volatile ListAttribute<C,D> list;
    public static volatile MapAttribute<C,Integer,D> map;
    public static volatile SingularAttribute<C,String> name;
    public static volatile SetAttribute<C,D> set;
}
