/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;
import javax.persistence.metamodel.Collection;
import javax.persistence.metamodel.List;
import javax.persistence.metamodel.Map;
import javax.persistence.metamodel.Set;

@javax.persistence.metamodel.TypesafeMetamodel
(value=org.apache.openjpa.persistence.criteria.C.class)
public class C_ {
    public static volatile Collection<C,D> coll;
    public static volatile Attribute<C,Long> id;
    public static volatile List<C,D> list;
    public static volatile Map<C,Integer,D> map;
    public static volatile Attribute<C,String> name;
    public static volatile Set<C,D> set;
}
