/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Contact.class)
public class Contact_ {
    public static volatile SingularAttribute<Contact,Address> address;
    public static volatile ListAttribute<Contact,Phone> phones;
}
