/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;
import javax.persistence.metamodel.List;

@javax.persistence.metamodel.TypesafeMetamodel(
    value=org.apache.openjpa.persistence.criteria.Course.class)
public class Course_ {
    public static volatile Attribute<Course,Long> id;
    public static volatile Attribute<Course,String> name;
    public static volatile List<Course,Student> studentWaitList;
}
