/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Course.class)
public class Course_ {
    public static volatile SingularAttribute<Course,Long> id;
    public static volatile SingularAttribute<Course,String> name;
    public static volatile ListAttribute<Course,Student> studentWaitList;
}
