/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;
import javax.persistence.metamodel.List;

@javax.persistence.metamodel.TypesafeMetamodel(
    value=org.apache.openjpa.persistence.criteria.CreditCard.class)
public class CreditCard_ {
    public static volatile Attribute<CreditCard,Customer> customer;
    public static volatile Attribute<CreditCard,Long> id;
    public static volatile List<CreditCard,TransactionHistory> 
        transactionHistory;
}
