/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.CreditCard.class)
public class CreditCard_ {
    public static volatile SingularAttribute<CreditCard,Customer> customer;
    public static volatile SingularAttribute<CreditCard,Long> id;
    public static volatile ListAttribute<CreditCard,TransactionHistory> transactionHistory;
}
