/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;
import javax.persistence.metamodel.List;
import javax.persistence.metamodel.Set;

@javax.persistence.metamodel.TypesafeMetamodel(
    value=org.apache.openjpa.persistence.criteria.Customer.class)
public class Customer_ {
    public static volatile Attribute<Customer,Long> accountNum;
    public static volatile List<Customer,Account> accounts;
    public static volatile Attribute<Customer,Address> address;
    public static volatile Attribute<Customer,Integer> balanceOwed;
    public static volatile Attribute<Customer,Integer> filledOrderCount;
    public static volatile Attribute<Customer,String> firstName;
    public static volatile Attribute<Customer,Long> id;
    public static volatile Attribute<Customer,String> lastName;
    public static volatile Attribute<Customer,String> name;
    public static volatile Set<Customer,Order> orders;
    public static volatile Attribute<Customer,Integer> status;
    public static volatile Attribute<Customer,Customer.CreditRating> 
        creditRating;
}
