/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel
(value=org.apache.openjpa.persistence.criteria.D.class)
public class D_ {
    public static volatile Attribute<D,C> c;
    public static volatile Attribute<D,Long> id;
    public static volatile Attribute<D,String> name;
}
