/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.D.class)
public class D_ {
    public static volatile SingularAttribute<D,C> c;
    public static volatile SingularAttribute<D,Long> id;
    public static volatile SingularAttribute<D,String> name;
}
