/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;
import javax.persistence.metamodel.Set;

@javax.persistence.metamodel.TypesafeMetamodel(value=org.apache.openjpa.persistence.criteria.Department.class)
public class Department_ {
    public static volatile Attribute<Department,Integer> deptNo;
    public static volatile Set<Department,Employee> employees;
    public static volatile Attribute<Department,String> name;
}
