/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Department.class)
public class Department_ {
    public static volatile SingularAttribute<Department,Integer> deptNo;
    public static volatile SetAttribute<Department,Employee> employees;
    public static volatile SingularAttribute<Department,String> name;
}
