/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import java.util.Date;
import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel(
    value=org.apache.openjpa.persistence.criteria.Dependent.class)
public class Dependent_ {
    public static volatile Attribute<Dependent,Integer> curStatusId;
    public static volatile Attribute<Dependent,Employee> emp;
    public static volatile Attribute<Dependent,Date> endDate;
    public static volatile Attribute<Dependent,DependentId> id;
}
