/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import java.util.Date;
import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel(
    value=org.apache.openjpa.persistence.criteria.DependentId.class)
public class DependentId_ {
    public static volatile Attribute<DependentId,Date> effDate;
    public static volatile Attribute<DependentId,Long> empid;
    public static volatile Attribute<DependentId,String> name;
}
