/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.DependentId.class)
public class DependentId_ {
    public static volatile SingularAttribute<DependentId,Date> effDate;
    public static volatile SingularAttribute<DependentId,Long> empid;
    public static volatile SingularAttribute<DependentId,String> name;
}
