/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Dependent.class)
public class Dependent_ {
    public static volatile SingularAttribute<Dependent,Integer> curStatusId;
    public static volatile SingularAttribute<Dependent,Employee> emp;
    public static volatile SingularAttribute<Dependent,Date> endDate;
    public static volatile SingularAttribute<Dependent,DependentId> id;
}
