/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel
(value=org.apache.openjpa.persistence.criteria.Employee.class)
public class Employee_ {
    public static volatile Attribute<Employee,Contact> contactInfo;
    public static volatile Attribute<Employee,Department> department;
    public static volatile Attribute<Employee,Integer> empId;
    public static volatile Attribute<Employee,FrequentFlierPlan> frequentFlierPlan;
    public static volatile Attribute<Employee,Manager> manager;
    public static volatile Attribute<Employee,String> name;
    public static volatile Attribute<Employee,Integer> rating;
    public static volatile Attribute<Employee,Long> salary;
    public static volatile Attribute<Employee,Employee> spouse;
}
