/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;


@javax.persistence.metamodel.TypesafeMetamodel
(value=org.apache.openjpa.persistence.criteria.FemaleUser.class)
public class FemaleUser_ extends CompUser_  {
}
