/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.FrequentFlierPlan.class)
public class FrequentFlierPlan_ {
    public static volatile SingularAttribute<FrequentFlierPlan,Integer> annualMiles;
    public static volatile SingularAttribute<FrequentFlierPlan,String> id;
    public static volatile SingularAttribute<FrequentFlierPlan,String> name;
}
