/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Item.class)
public class Item_ {
    public static volatile SingularAttribute<Item,Integer> id;
    public static volatile SingularAttribute<Item,String> name;
    public static volatile MapAttribute<Item,String,Photo> photos;
}
