/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.LineItem.class)
public class LineItem_ {
    public static volatile SingularAttribute<LineItem,Double> cost;
    public static volatile SingularAttribute<LineItem,Integer> id;
    public static volatile SingularAttribute<LineItem,Order> order;
    public static volatile SingularAttribute<LineItem,Double> price;
    public static volatile SingularAttribute<LineItem,Product> product;
    public static volatile SingularAttribute<LineItem,Integer> quantity;
}
