/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel
(value=org.apache.openjpa.persistence.criteria.LineItem.class)
public class LineItem_ {
    public static volatile Attribute<LineItem,Double> cost;
    public static volatile Attribute<LineItem,Integer> id;
    public static volatile Attribute<LineItem,Order> order;
    public static volatile Attribute<LineItem,Double> price;
    public static volatile Attribute<LineItem,Product> product;
    public static volatile Attribute<LineItem,Integer> quantity;
}
