/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import java.sql.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Magazine.class)
public class Magazine_ {
    public static volatile SingularAttribute<Magazine,Date> datePublished;
    public static volatile SingularAttribute<Magazine,Integer> id;
    public static volatile SingularAttribute<Magazine,Publisher> idPublisher;
    public static volatile SingularAttribute<Magazine,String> name;
}
