/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import java.math.BigDecimal;
import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel(value=org.apache.openjpa.persistence.criteria.Manager.class)
@javax.annotation.Generated(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat May 09 23:22:02 PDT 2009")
public class Manager_ {
    public static volatile Attribute<Manager,Department> department;
    public static volatile Attribute<Manager,Integer> id;
    public static volatile Attribute<Manager,String> name;
    public static volatile Attribute<Manager,BigDecimal> salary;
}
