/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import java.math.BigDecimal;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Manager.class)
public class Manager_ {
    public static volatile SingularAttribute<Manager,Department> department;
    public static volatile SingularAttribute<Manager,Integer> id;
    public static volatile SingularAttribute<Manager,String> name;
    public static volatile SingularAttribute<Manager,BigDecimal> salary;
}
