/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel
(value=org.apache.openjpa.persistence.criteria.Movie.class)
public class Movie_ {
    public static volatile Attribute<Movie,Integer> id;
    public static volatile Attribute<Movie,String> title;
}
