/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Movie.class)
public class Movie_ {
    public static volatile SingularAttribute<Movie,Integer> id;
    public static volatile SingularAttribute<Movie,String> title;
}
