/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;
import javax.persistence.metamodel.List;

@javax.persistence.metamodel.TypesafeMetamodel(value=org.apache.openjpa.persistence.criteria.Order.class)
public class Order_ {
    public static volatile Attribute<Order,Integer> count;
    public static volatile Attribute<Order,Customer> customer;
    public static volatile Attribute<Order,Integer> id;
    public static volatile List<Order,LineItem> lineItems;
    public static volatile Attribute<Order,Integer> quantity;
    public static volatile Attribute<Order,Double> totalCost;
}
