/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import java.sql.Timestamp;

import javax.persistence.metamodel.Attribute;
import javax.persistence.metamodel.List;

@javax.persistence.metamodel.TypesafeMetamodel(
    value=org.apache.openjpa.persistence.criteria.Order.class)
public class Order_ {
    public static volatile Attribute<Order,Integer> count;
    public static volatile Attribute<Order,Customer> customer;
    public static volatile Attribute<Order,Integer> id;
    public static volatile List<Order,LineItem> lineItems;
    public static volatile Attribute<Order,Integer> quantity;
    public static volatile Attribute<Order,Double> totalCost;
    public static volatile Attribute<Order,Boolean> delivered;
    public static volatile Attribute<Order,Timestamp> orderTs;
}
