/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Person.class)
public class Person_ {
    public static volatile SingularAttribute<Person,Integer> id;
    public static volatile SingularAttribute<Person,String> name;
    public static volatile SetAttribute<Person,String> nickNames;
}
