/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;
import javax.persistence.metamodel.Set;

@javax.persistence.metamodel.TypesafeMetamodel
(value=org.apache.openjpa.persistence.criteria.Person.class)
public class Person_ {
    public static volatile Attribute<Person,Integer> id;
    public static volatile Attribute<Person,String> name;
    public static volatile Set<Person,String> nickNames;
}
