/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;
import javax.persistence.metamodel.Collection;

@javax.persistence.metamodel.TypesafeMetamodel(value=org.apache.openjpa.persistence.criteria.Phone.class)
public class Phone_ {
    public static volatile Collection<Phone,Employee> employees;
    public static volatile Attribute<Phone,Integer> id;
    public static volatile Attribute<Phone,String> vendor;
}
