/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.CollectionAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Phone.class)
public class Phone_ {
    public static volatile CollectionAttribute<Phone,Employee> employees;
    public static volatile SingularAttribute<Phone,Integer> id;
    public static volatile SingularAttribute<Phone,String> vendor;
}
