/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Photo.class)
public class Photo_ {
    public static volatile SingularAttribute<Photo,Integer> id;
    public static volatile SingularAttribute<Photo,String> label;
}
