/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel(value=org.apache.openjpa.persistence.criteria.Product.class)
public class Product_ {
    public static volatile Attribute<Product,Integer> pid;
    public static volatile Attribute<Product,String> productType;
    public static volatile Attribute<Product,Long> version;
}
