/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Product.class)
public class Product_ {
    public static volatile SingularAttribute<Product,Integer> pid;
    public static volatile SingularAttribute<Product,String> productType;
    public static volatile SingularAttribute<Product,Long> version;
}
