/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;
import javax.persistence.metamodel.Set;

@javax.persistence.metamodel.TypesafeMetamodel(
    value=org.apache.openjpa.persistence.criteria.Publisher.class)
public class Publisher_ {
    public static volatile Attribute<Publisher,Integer> id;
    public static volatile Set<Publisher,Magazine> magazineCollection;
    public static volatile Attribute<Publisher,String> name;
}
