/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Publisher.class)
public class Publisher_ {
    public static volatile SingularAttribute<Publisher,Integer> id;
    public static volatile SetAttribute<Publisher,Magazine> magazineCollection;
    public static volatile SingularAttribute<Publisher,String> name;
    public static volatile SingularAttribute<Publisher,Long> serialVersionUID;
}
