/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel(
    value=org.apache.openjpa.persistence.criteria.Semester.class)
public class Semester_ {
    public static volatile Attribute<Semester,Integer> id;
    public static volatile Attribute<Semester,String> name;
}
