/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Semester.class)
public class Semester_ {
    public static volatile SingularAttribute<Semester,Integer> id;
    public static volatile SingularAttribute<Semester,String> name;
}
