/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Student.class)
public class Student_ {
    public static volatile MapAttribute<Student,Course,Semester> enrollment;
    public static volatile SingularAttribute<Student,Integer> id;
    public static volatile SingularAttribute<Student,String> name;
}
