/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import java.sql.Timestamp;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.TransactionHistory.class)
public class TransactionHistory_ {
    public static volatile SingularAttribute<TransactionHistory,String> details;
    public static volatile SingularAttribute<TransactionHistory,Integer> id;
    public static volatile SingularAttribute<TransactionHistory,Timestamp> transDate;
}
