/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;


@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.Transaction.class)
public class Transaction_ {
}
