/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import java.sql.Timestamp;
import javax.persistence.metamodel.Attribute;

@javax.persistence.metamodel.TypesafeMetamodel(value=org.apache.openjpa.persistence.criteria.TransactionHistory.class)
@javax.annotation.Generated(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat May 09 23:22:02 PDT 2009")
public class TransactionHistory_ {
    public static volatile Attribute<TransactionHistory,String> details;
    public static volatile Attribute<TransactionHistory,Integer> id;
    public static volatile Attribute<TransactionHistory,Timestamp> transDate;
}
