/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.apache.openjpa.persistence.criteria;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.apache.openjpa.persistence.criteria.VideoStore.class)
public class VideoStore_ {
    public static volatile SingularAttribute<VideoStore,Integer> id;
    public static volatile SingularAttribute<VideoStore,Address> location;
    public static volatile SingularAttribute<VideoStore,String> name;
    public static volatile MapAttribute<VideoStore,Movie,Integer> videoInventory;
}
